### ISSUE TITLE
Support `lium sync` to checkout public repository

### ISSUE THREAD

**Issue by 4n12i** [google/lium#167]
Users cannot sync public cros repo.

**Comment by hikalium** [comment]
https://github.com/google/lium/commit/56dd7ba971258daa6cbfe0c91670a2550761cd75

Maybe this commit in my personal-tree can help the idea!

**Comment by 4n12i** [comment]
@hikalium 
Thank you for letting me know!!

Do users ever switch between checking out public/internal repo? If so, how about switching them by the `is_internal` flag?
029e213d5b9eb4101dbd86f0cba99898a87476bf
