### ISSUE TITLE
`lium vm setup` requires to have `--repo` option

### ISSUE THREAD

**Issue by mhiramat** [google/lium#180]
I tried `lium vm setup` but it requires `--repo` option
```
/work/lium$ lium vm setup 
Error: betty.sh doesn't exist in /work/lium. Please consider specifying --repo option.
```
But when I pass that option, it does not recognize the option.
```
/work/lium$ lium vm setup --repo /work/chromiumos
Unrecognized argument: --repo

Run lium --help for more information.
```

**Comment by 4n12i** [comment]
Sorry, I forgot to update the error message. The option to specify the betty script path is correctly the `--arc` option.I fixed it so it should work.   

Thank you for letting me know!!
