### ISSUE TITLE
Determine the option name to specify repo root directories for ChromeOS and Android

### ISSUE THREAD

**Issue by 4n12i** [google/lium#218]
Currently they are `--cros` and `--arc`, but @brandonpollack23 suggests changing them to `--cros-repo` and `--arc-repo`.  

Context: https://github.com/google/lium/pull/191 https://github.com/google/lium/pull/197

**Comment by 4n12i** [comment]
@brandonpollack23 
Please reply to this comment https://github.com/google/lium/pull/197#issuecomment-1860338164 here.

**Comment by hikalium** [comment]
We decided not to change the arg parameter name to make it simple as lium is a front-end command line tool used by hand.
