### ISSUE TITLE
show repo sync progress while `lium sync` 

### ISSUE THREAD

**Issue by hikalium** [google/lium#30]
Not showing progress on lium sync is not user friendly. display some progress to make it clear that it is not stuck but it is in progress...

**Comment by brandonpollack23** [comment]
https://docs.rs/indicatif/latest/indicatif/ might help with that, along with https://crates.io/crates/tracing-indicatif to integrate it with the logging work in #88

**Comment by brandonpollack23** [comment]
repo sync already outputs a percentage and overwrites it's line using [console control characters](https://man7.org/linux/man-pages/man4/console_codes.4.html), so all we need to do is read the std out of the process, cut out the percentage (using regex or simple string splitting) and turn that into an int as an input for indicatif.  

Then integrate indacatif with the tracing system with the tracing-indicatif crate.

**Comment by hikalium** [comment]
Now it is implemented by @4n12i so closing this as Fixed. Thank you!
