### ISSUE TITLE
Pipe-processing friendly output for servo list output

### ISSUE THREAD

**Issue by cynthia** [google/lium#40]
Right now, the default output for `servo list` is JSON.

It would be nice if we didn't need to rely on arcane methods to massage the output into something usable. For example, here is how you get a list of the usb devices so that it can be processed by a shell script:

    lium servo list | jq -r '.[] | map(.serial + ": " + .usb_sysfs_path)[]' \
    | awk '{print $2 " " $1;}' | sort | tr -d ':'

Given that this is a CLI first, it'd make sense to make the default output pipe-processing friendly, and make JSON output an opt-in (as that would be more likely something that would be machine-processed).

**Comment by hikalium** [comment]
Thanks for the issue! Actually, I just started working on updating the interfaces of servo related commands as Unix-commands-friendly and machine-friendly with --json flag. Let me take the issue and work on a fix.
