### ISSUE TITLE
Add AB update option to kernel deploy

### ISSUE THREAD

**Issue by mhiramat** [google/lium#42]
Add `--ab_update` option to the kernel package deploy.

**Comment by HidenoriKobayashi** [comment]
Do you mean to add it by default?

There are times I want to update the same partition, mostly because I have a custom built package deployed in the current chroot but not in the other one. It works for me if there will be an option to remove that flag.

**Comment by mhiramat** [comment]
No, I would like to add that option to `lium deploy` (ignored if the package is not host kernel).

**Comment by HidenoriKobayashi** [comment]
Thanks for clarification! As long as it is an option, then it's fine by me. And the PR looks good to me :+1:
